# Generated by Django 4.2.11 on 2026-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('funcao', models.CharField(max_length=100)),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
