# Generated by Django 4.2.11 on 2026-01-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='desligado',
            field=models.BooleanField(default=False),
        ),
    ]
